version: "3"

services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"
      - "4222:4222"

  client-getaway:
    build: ./client-getaway
    ports:
      - ${CLIENT_GATEWAY}:3000
    volumes:
      - ./client-getaway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  product-microservice:
    build: ./productos-ms1-nest
    volumes:
      - ./productos-ms1-nest/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  order-microservice:
    build: ./orders-ms
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://postgres:jarry@postgres:5432/orders?schema=public
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jarry
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:



